# Generated by Django 2.1.15 on 2021-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('cena', models.IntegerField(null=True)),
                ('jakosc', models.CharField(max_length=255)),
                ('stron', models.IntegerField()),
                ('tytul', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('url2', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
